version: '3.8'

services:
  # 1. Единая СУБД PostgreSQL для Data Vault 2.0 и метаданных
  vkr_final_postgres:
    image: postgres:15-alpine
    container_name: vkr_postgres_container
    networks:
      - vkr_network
    environment:
      POSTGRES_USER: db_security_admin
      POSTGRES_PASSWORD: strong_security_password_123
      POSTGRES_DB: vkr_art_integration_dwh
      # ИСПРАВЛЕНИЕ: Выделяем память СУБД для работы с Big Data хэшами
      PGOPTIONS: "-c shared_buffers=512MB -c work_mem=128MB -c maintenance_work_mem=256MB"
    ports:
      - "5432:5432"  
    volumes:
      - vkr_new_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_security_admin -d vkr_art_integration_dwh"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Оркестратор задач Apache Airflow
  vkr_final_airflow:
    image: apache/airflow:2.7.2-python3.11
    container_name: vkr_airflow_container
    networks:
      - vkr_network
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_lake_clean:/opt/airflow/data_lake_clean
      - .:/opt/airflow/src
    command: >
      bash -c "airflow db init && 
      airflow users create --username admin --firstname Admin --lastname Admin --role Admin --email admin@example.com --password admin && 
      airflow webserver & airflow scheduler"
    depends_on:
      vkr_final_postgres:
        condition: service_healthy  
    restart: unless-stopped

  # 3. Аналитическая СУБД ClickHouse для слоя витрин
  vkr_final_clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: vkr_clickhouse_container
    networks:
      - vkr_network
    environment:
      - CLICKHOUSE_DB=art_marts_db
      - CLICKHOUSE_USER=clickhouse_analyst
      - CLICKHOUSE_PASSWORD=SecureClickPass2026
    ports:
      - "8123:8123" 
      - "9000:9000" 
    volumes:
      - vkr_ch_data_v2:/var/lib/clickhouse
    restart: unless-stopped

  # 4. НОВАЯ КРАСИВАЯ BI-ПЛАТФОРМА METABASE (ПОРТ 3000)
  vkr_final_metabase:
    image: metabase/metabase:latest
    container_name: vkr_metabase_container
    networks:
      - vkr_network
    ports:
      - "3000:3000"
    volumes:
      - vkr_metabase_data:/metabase.db
    restart: unless-stopped
    depends_on:
      vkr_final_postgres:
        condition: service_healthy

networks:
  vkr_network:
    driver: bridge

volumes:
  vkr_new_pgdata:
    driver: local
  vkr_ch_data_v2:
    driver: local
  vkr_metabase_data:
    driver: local